### ISSUE TITLE
Consider a get-property function?

### ISSUE THREAD

**Issue by dieggsy** [ec1oud/dbus-egg#7]
I found it rather annoying to need two different contexts for getting properties and calling methods, and found that dbus properties are something common enough to perhaps warrant their own generalized scheme function that could work on any context, provided it has a `org.freedesktop.DBus.Properties` interface.

I've been using something like this, for example:

```scheme
(use (prefix dbus dbus:))

(define (get-property context prop)
  (let* ((prop (->string prop))
         (bus (vector-ref context 1))
         (service (vector-ref context 2))
         (path (vector-ref context 3))
         (old-interface (vector-ref context 4))
         (context
          (dbus:make-context
           bus: bus
           service: service
           path: path
           interface: 'org.freedesktop.DBus.Properties))
         (raw
          (handle-exceptions err #f
            (dbus:call context "Get" (symbol->string old-interface) prop))))
    (and raw (car raw))))
```
I guess the `handle-exceptions` bit is sorta iffy, wondering if you think it's worth including something like this and regardless how it could be improved.

**Comment by ec1oud** [comment]
Your patch is merged.  I haven't been using this stuff for a long time so I can't easily figure out all the implications of this, but glad it's working for you.
